### PR TITLE
Put timer on title's page #5

### PR DESCRIPTION
**Pull request by shakegioh**
Now the title also have a countdown

### CODE REVIEW

**Comment by willianjusten** [comment]
Wow, react has components for everything <3

**Comment by afonsopacifer** [comment]
Another cool component to the collection! 
Thank's @shakegioh 👍

**Comment by afonsopacifer** [comment]
@shakegioh
**Tip:** In the next PR , send for `developement` branch  :)

**Comment by shakegioh** [comment]
Oh, i'm sorry. I tried to send to development branch but I guess I got confused, I will pay more attention next time.

**Comment by afonsopacifer** [comment]
Relax ;)

**Pull request merged**
