### PR TITLE
Shortcuts

### PR DESCRIPTION
**Pull request by shakegioh**
- Space: Play
- Ctrl + Left: Toggle mode
- Ctrl + Right: Toggle mode

### CODE REVIEW

**Comment by shakegioh** [comment]
I'm sorry, looks like i did a pull request to the master branch again, but wasn't intentionally, I don't know how to do it right yet, can I cancel this and do it again?

**Comment by afonsopacifer** [comment]
its OK! I am using the master now ;)
I deleted the development , was giving problems!

**Comment by afonsopacifer** [comment]
Sorry for deplay :)
Thanks =D

**Comment by afonsopacifer** [comment]
@shakegioh Great job man 👊

**Comment by shakegioh** [comment]
Thank you a lot!!

**Pull request merged**
